// <auto-generated />
namespace EntitiesCodeFirstMethod.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class thirdTry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thirdTry));
        
        string IMigrationMetadata.Id
        {
            get { return "202205122106551_thirdTry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
